/**
 * CSR (Certificate Signing Request) generator utility
 * Uses WebCrypto API + @peculiar/x509 for client-side key generation and CSR creation
 *
 * SECURITY CRITICAL: Private keys are generated client-side and never sent to the server.
 * Keys exist only in memory during generation and must be cleared after use.
 *
 * POC validation tests available via: yarn test:poc
 */

import * as x509 from '@peculiar/x509';
import type {
  KeyType,
  CsrSubjectFields,
  CsrSanFields,
  GeneratedCsrResult,
} from '@krakenkey/shared';

/**
 * Checks if WebCrypto API is available in the current browser
 */
export function isBrowserCompatible(): boolean {
  return typeof window !== 'undefined' &&
         window.crypto !== undefined &&
         window.crypto.subtle !== undefined;
}

/**
 * Generates a cryptographic key pair based on the selected key type
 * Uses WebCrypto API for secure key generation
 *
 * @param keyType - The type of key to generate (RSA-2048, RSA-4096, ECDSA-P256, ECDSA-P384)
 * @returns Promise<CryptoKeyPair> - Key pair with private and public keys
 * @throws Error if key generation fails or browser doesn't support the algorithm
 */
export async function generateKeyPair(keyType: KeyType): Promise<CryptoKeyPair> {
  if (!isBrowserCompatible()) {
    throw new Error('WebCrypto API not supported in this browser');
  }

  try {
    switch (keyType) {
      case 'RSA-2048':
        return await crypto.subtle.generateKey(
          {
            name: 'RSASSA-PKCS1-v1_5',
            modulusLength: 2048,
            publicExponent: new Uint8Array([1, 0, 1]), // 65537
            hash: 'SHA-256',
          },
          true, // extractable
          ['sign', 'verify']
        ) as CryptoKeyPair;

      case 'RSA-4096':
        return await crypto.subtle.generateKey(
          {
            name: 'RSASSA-PKCS1-v1_5',
            modulusLength: 4096,
            publicExponent: new Uint8Array([1, 0, 1]),
            hash: 'SHA-256',
          },
          true,
          ['sign', 'verify']
        ) as CryptoKeyPair;

      case 'ECDSA-P256':
        return await crypto.subtle.generateKey(
          {
            name: 'ECDSA',
            namedCurve: 'P-256',
          },
          true,
          ['sign', 'verify']
        ) as CryptoKeyPair;

      case 'ECDSA-P384':
        return await crypto.subtle.generateKey(
          {
            name: 'ECDSA',
            namedCurve: 'P-384',
          },
          true,
          ['sign', 'verify']
        ) as CryptoKeyPair;

      default:
        throw new Error(`Unsupported key type: ${keyType}`);
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Key generation failed: ${message}`);
  }
}

/**
 * Creates a Certificate Signing Request (CSR) from key pair and subject information
 *
 * @param keyPair - Cryptographic key pair generated by generateKeyPair()
 * @param subject - X.509 subject fields (CN, O, OU, L, ST, C)
 * @param sans - Subject Alternative Names (DNS, IP, email)
 * @param keyType - Original key type for determining signing algorithm
 * @returns Promise<string> - PEM-encoded CSR
 * @throws Error if CSR creation fails
 */
export async function createCsr(
  keyPair: CryptoKeyPair,
  subject: CsrSubjectFields,
  sans: CsrSanFields,
  keyType: KeyType
): Promise<string> {
  try {
    // Build subject DN (Distinguished Name) string
    // Escape special chars per RFC 4514: comma, plus, quotes, backslash, angle brackets, semicolon
    const escapeDnValue = (val: string): string =>
      val.replace(/([,+="\\<>;#])/g, '\\$1')
         .replace(/^ /, '\\ ')   // Leading space
         .replace(/ $/, '\\ ');   // Trailing space

    const subjectParts: string[] = [];
    subjectParts.push(`CN=${escapeDnValue(subject.commonName)}`);
    if (subject.organization) subjectParts.push(`O=${escapeDnValue(subject.organization)}`);
    if (subject.organizationalUnit) subjectParts.push(`OU=${escapeDnValue(subject.organizationalUnit)}`);
    if (subject.locality) subjectParts.push(`L=${escapeDnValue(subject.locality)}`);
    if (subject.state) subjectParts.push(`ST=${escapeDnValue(subject.state)}`);
    if (subject.country) subjectParts.push(`C=${escapeDnValue(subject.country)}`);

    const subjectDn = subjectParts.join(',');

    // Determine signing algorithm based on key type
    let signingAlgorithm: Algorithm | EcdsaParams;
    if (keyType.startsWith('RSA')) {
      signingAlgorithm = { name: 'RSASSA-PKCS1-v1_5' } as Algorithm;
    } else if (keyType === 'ECDSA-P256') {
      signingAlgorithm = { name: 'ECDSA', hash: { name: 'SHA-256' } } as EcdsaParams;
    } else if (keyType === 'ECDSA-P384') {
      signingAlgorithm = { name: 'ECDSA', hash: { name: 'SHA-384' } } as EcdsaParams;
    } else {
      throw new Error(`Unknown key type for signing: ${keyType}`);
    }

    // Build Subject Alternative Names as JsonGeneralName entries
    const sanEntries: x509.JsonGeneralName[] = [];

    // Add all DNS names (including CN, per RFC 2818)
    const allDnsNames = new Set([subject.commonName, ...sans.dnsNames]);
    allDnsNames.forEach(dns => {
      if (dns) sanEntries.push({ type: 'dns', value: dns });
    });

    // Add IP addresses
    sans.ipAddresses.forEach(ip => {
      if (ip) sanEntries.push({ type: 'ip', value: ip });
    });

    // Add email addresses
    sans.emailAddresses.forEach(email => {
      if (email) sanEntries.push({ type: 'email', value: email });
    });

    // Create extensions array
    const extensions: x509.Extension[] = [];
    if (sanEntries.length > 0) {
      extensions.push(
        new x509.SubjectAlternativeNameExtension(sanEntries)
      );
    }

    // Generate CSR
    const csr = await x509.Pkcs10CertificateRequestGenerator.create({
      name: subjectDn,
      keys: keyPair,
      signingAlgorithm,
      extensions,
    });

    // Export to PEM format
    return csr.toString('pem');
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`CSR creation failed: ${message}`);
  }
}

/**
 * Exports a private key to PEM format (PKCS#8)
 *
 * SECURITY WARNING: This contains sensitive key material. Handle with care.
 * The returned string should be cleared from memory after user saves it.
 *
 * @param privateKey - CryptoKey to export
 * @returns Promise<string> - PEM-encoded private key
 * @throws Error if export fails
 */
export async function exportPrivateKeyToPem(privateKey: CryptoKey): Promise<string> {
  try {
    const exported = await crypto.subtle.exportKey('pkcs8', privateKey);
    return pemEncode(exported, 'PRIVATE KEY');
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Private key export failed: ${message}`);
  }
}

/**
 * Exports a public key to PEM format (SPKI)
 *
 * @param publicKey - CryptoKey to export
 * @returns Promise<string> - PEM-encoded public key
 * @throws Error if export fails
 */
export async function exportPublicKeyToPem(publicKey: CryptoKey): Promise<string> {
  try {
    const exported = await crypto.subtle.exportKey('spki', publicKey);
    return pemEncode(exported, 'PUBLIC KEY');
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Public key export failed: ${message}`);
  }
}

/**
 * Encodes binary data as PEM format
 *
 * @param buffer - ArrayBuffer containing key data
 * @param label - PEM label (e.g., "PRIVATE KEY", "PUBLIC KEY")
 * @returns PEM-encoded string
 */
function pemEncode(buffer: ArrayBuffer, label: string): string {
  const base64 = arrayBufferToBase64(buffer);
  const lines = base64.match(/.{1,64}/g) || [];
  return `-----BEGIN ${label}-----\n${lines.join('\n')}\n-----END ${label}-----`;
}

/**
 * Converts ArrayBuffer to base64 string
 */
function arrayBufferToBase64(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

/**
 * Main function: Generates a complete CSR with private/public keys
 *
 * This is the primary entry point for the CSR generator UI.
 * All cryptographic operations happen client-side.
 *
 * @param keyType - Type of key to generate
 * @param subject - X.509 subject fields
 * @param sans - Subject Alternative Names
 * @returns Promise<GeneratedCsrResult> - Complete CSR package
 * @throws Error if any step fails
 */
export async function generateCsr(
  keyType: KeyType,
  subject: CsrSubjectFields,
  sans: CsrSanFields
): Promise<GeneratedCsrResult> {
  if (!isBrowserCompatible()) {
    throw new Error(
      'Your browser does not support cryptographic operations. ' +
      'Please use a modern browser (Chrome, Firefox, Safari, or Edge).'
    );
  }

  try {
    // Step 1: Generate key pair
    const keyPair = await generateKeyPair(keyType);

    // Step 2: Create CSR
    const csrPem = await createCsr(keyPair, subject, sans, keyType);

    // Step 3: Export keys to PEM
    const privateKeyPem = await exportPrivateKeyToPem(keyPair.privateKey);
    const publicKeyPem = await exportPublicKeyToPem(keyPair.publicKey);

    // Determine algorithm and key size
    const algorithm = keyType.startsWith('RSA') ? 'RSA' : 'ECDSA';
    const keySize = keyType === 'RSA-2048' ? 2048 :
                    keyType === 'RSA-4096' ? 4096 :
                    keyType === 'ECDSA-P256' ? 256 :
                    384; // ECDSA-P384

    return {
      csrPem,
      privateKeyPem,
      publicKeyPem,
      algorithm,
      keySize,
      keyType,
    };
  } catch (error) {
    // Re-throw with sanitized error message (no key material)
    const message = error instanceof Error ? error.message : 'Unknown error';
    throw new Error(sanitizeErrorMessage(message));
  }
}

/**
 * Sanitizes error messages to prevent leaking key material
 * Removes any PEM-formatted content and long hex strings
 */
export function sanitizeErrorMessage(message: string): string {
  // Remove PEM blocks
  let sanitized = message.replace(
    /-----BEGIN[\s\S]*?-----END[^-]+-----/g,
    '[REDACTED]'
  );

  // Remove long hex strings (likely key material)
  sanitized = sanitized.replace(/[0-9a-fA-F]{33,}/g, '[HEX_REDACTED]');

  // Generic message for crypto-related errors
  if (sanitized.toLowerCase().includes('crypto') ||
      sanitized.toLowerCase().includes('subtle')) {
    return 'Cryptographic operation failed. Please try again or contact support.';
  }

  return sanitized;
}

/**
 * Gets human-readable security level description for a key type
 */
export function getSecurityLevel(keyType: KeyType): string {
  switch (keyType) {
    case 'RSA-2048':
      return '~112-bit security';
    case 'RSA-4096':
      return '~152-bit security';
    case 'ECDSA-P256':
      return '~128-bit security (~3072-bit RSA equivalent)';
    case 'ECDSA-P384':
      return '~192-bit security (~7600-bit RSA equivalent)';
    default:
      return 'Unknown';
  }
}

/**
 * Gets estimated generation time for a key type
 */
export function getGenerationTime(keyType: KeyType): string {
  switch (keyType) {
    case 'RSA-2048':
      return '~1-2 seconds';
    case 'RSA-4096':
      return '~2-5 seconds';
    case 'ECDSA-P256':
    case 'ECDSA-P384':
      return '<1 second';
    default:
      return 'Unknown';
  }
}
